config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from yoolink.views import load_index, team, shop, detail, impressum, datenschutz, cookies
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include

from django.contrib.sitemaps.views import sitemap
from yoolink.sitemaps import StaticViewSitemap, BlogSitemap, ProductSitemap
from yoolink.ycms.views import cart_verify_success_view, cart_view, order_verify_success_view, order_verify_view

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'product': ProductSitemap,
}

urlpatterns = [
    path("", view=load_index, name="home"),
    path("team/", view=team, name="team"),
    path("products/", view=shop, name="products"),
    path("products/<int:product_id>-<slug:slug>/", view=detail, name="product-detail"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Your stuff: custom urls includes go here
    path("", include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
    path("impressum/", view=impressum, name="impressum"),
    # path("kontakt/", view=kontaktform, name="kontakt"),
    path("datenschutz/", view=datenschutz, name="datenschutz"),
    path("cookies/", view=cookies, name="cookies"),
    path("cms/", include("yoolink.ycms.urls", namespace="ycms")),
    path("blog/", include("yoolink.blog.urls", namespace="blog")),
    
    path('cart/', cart_view, name='cart-view'),
    path('cart/success/', cart_verify_success_view, name='cart-verify-success-view'),

    path('order/verify/', order_verify_view, name='order-verify'),
    path('order/success/', order_verify_success_view, name='order-verify-success-view'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

yoolink/blog/urls.py
from django.urls import path, include

from .views import Load_Index_Blog, BlogDetailView


app_name = "blog"


urlpatterns = [
    path("", Load_Index_Blog.as_view(), name="blog"),
    path("<int:pk>-<slug:slug_title>/", BlogDetailView.as_view(), name="blog-detail"),
]

yoolink/users/urls.py
from django.urls import path

from yoolink.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

yoolink/ycms/urls.py
from django.urls import path, include
from . import views


app_name = "cms"
urlpatterns = [
    path("", views.upload, name="cms"),
    path("login/", views.Login_Cms, name="login"),
    path('logout/', views.custom_logout, name='logout'),
    # Images
    path('upload/', views.upload_view, name='upload'),
    path('upload/delete/<str:name>/', views.delete_file_by_name, name='upload-delete'),
    path('upload/post', views.file_upload_view, name='post-upload'),
    path('images/', views.images_view, name='images-view'),
    path('images/delete/<int:id>/', views.delete_file, name='image-delete'),
    path('images/update/<int:id>/', views.update_file, name='image-update'),
    path('images/all/', views.all_images, name="all-images"),
    # FAQ
    path('faq/sort/', views.update_faq_order, name='faq-sort'),
    path('faq/', views.faq_view, name='faq-view'),
    path('faq/update/', views.update_faq, name='faq-update'),
    path('faq/delete/<int:id>/', views.del_faq, name='faq-update'),
    # Blog
    path('blog/', views.blog_view, name='blog-view'),
    path('blog/add/', views.add_blog, name='blog-add'),
    path('blog/create/', views.create_blog, name='blog-create'),
    path('blog/<int:id>/', views.blog_details, name='blog-details'),
    path('blog/<int:id>/getCode/', views.blog_code, name='blog-code'),
    path('blog/<int:id>/delete/', views.delete_blog, name='blog-delete'),
    path('blog/<int:id>/update/', views.update_blog, name='blog-update'),
    # Galery
    path('galerien/', views.galerien, name='galerien'),
    path('galery/images/update/<int:id>/', views.update_galery_image, name='galery-update-img'),
    path('galery/create/', views.create_galery, name='galery-create'),
    path('galery/getImages/', views.get_galery_images, name='galery-get-images'),
    path('galery/delete-img/<int:id>/', views.delete_galery_img, name='delete-galery-img'),
    path('galery/<int:id>/', views.galery_view, name='galery-view'),
    path('galery/<int:id>/upload/', views.upload_galery_img, name='upload-galery-img'),
    path('galery/<int:id>/save/', views.save_galery, name='galery-save'),
    path('galery/<int:id>/delete/', views.delete_galery, name='galery-delete'),
    path('galerien/all/', views.all_galerien, name="all-galerien"),
    # Seiten
    path('seiten/', views.content_view, name='sites'),
    path('seiten/save/', views.saveTextContent, name='save_text_content'),
    path('seiten/hauptseite/', views.site_view_main, name='site_hauptseite'),
    path('seiten/hauptseite/Hero/', views.site_view_main_hero, name='site_hauptseite_hero'),
    path('seiten/hauptseite/Dienstleistung/', views.site_view_main_dienstleistungen, name='site_hauptseite_dienstleistung'),
    path('seiten/hauptseite/Workflow/', views.site_view_main_flow, name='site_hauptseite_workflow'),
    path('seiten/hauptseite/Kontakt/', views.site_view_main_contact, name='site_hauptseite_contact'),
    path('seiten/hauptseite/Produkte/', views.site_view_main_angebote, name='site_hauptseite_products'),
    
    path('seiten/team/', views.site_view_team, name='site_team'),
    path('seiten/team/Hero/', views.site_view_team_hero, name='site_team_hero'),
    path('seiten/team/Team/', views.site_view_team_team, name='site_team_team'),

    # Products
    path('products/', views.product_view, name='products'),
    path('products/search/', views.product_search, name='product_search'),
    # USER API Based search
    path('products/client/search/', views.search_products, name='product_client_search'),
    path('products/create/', views.product_create_view, name='product-create'),
    path('products/create/upload', views.product_create, name='product-create-upload'),
    path('products/<int:product_id>/<slug:slug>/', views.product_detail, name='product-detail'),
    path('products/<int:product_id>/<slug:slug>/update', views.product_update, name='product-detail-update'),
    path('products/<int:product_id>/<slug:slug>/delete', views.product_delete, name='product-detail-delete'),
    path('products/get_categories/', views.get_categories, name='get-categories'),
    path('products/get_brands/', views.get_brands, name='get-brands'),
    
    # ** START - Orders **

    path('api/cart/add/<int:product_id>/', views.add_to_cart, name='api-cart-add'),
    path('api/cart/', views.cart_items, name='api-cart'),
    path('api/cart/<int:order_item_id>/remove/', views.remove_from_cart, name='api-cart-remove'),
    path('api/cart/<int:order_item_id>/update-quantity/', views.update_quantity, name='api-cart-update-quantity'),
    path('api/cart/update/', views.update_cart_items, name='api-cart-update'),
    path('api/cart/verify/', views.verify_cart, name='api-cart-verify'),
    
    # Other Order Stuff
    path('api/order/verify/', views.verify_order, name='api-order-verify'),

    path('orders/', views.order_view, name='order-overview'),
    path('orders/<int:order_id>/', views.order_detail_view, name='order-detail-view'),
    # GET all orders by filter (as JSON)
    path('orders/filter/', views.get_orders, name='order-api'),
    # TODO: Still JSON Response. Change it to render view response
    path('api/orders/<int:order_id>/', views.get_order_by_id, name='get_order_by_id'),
    path('orders/<int:order_id>/update_order_status/', views.update_order_status_admin, name='update_order_status'),
    path('orders/<int:order_id>/delete/', views.delete_order, name='delete_order'),

    path('shop/', views.shop, name='shop'),
    # ** END - Orders **

    # Reviews
    path('reviews/<int:review_id>/delete_reviews/', views.delete_review, name='delete_review'),

    # Email
    path('email/request/', views.email_send, name='send-email'),
    
    # Settings
    path('settings/', views.user_settings_view, name='settings-view'),
    path('settings/update/', views.user_settings_update, name='settings-update'),
    
    # Opening Hours
    path('openinghours/', views.opening_hours_view, name='openinghours-view'),
    path('openinghours/update/', views.opening_hours_update, name='openinghours-update'),

]

yoolink/blog/models.py
from django.db import models

# Create your models here.

yoolink/designtemplates/models.py
from django.db import models

# Create your models here.

yoolink/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for YooLink.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

yoolink/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

yoolink/ycms/forms.py
from django import forms
from .models import fileentry, Blog

class fileform(forms.ModelForm):
    label = ''                      ### This hides the label next to the "Browse..." button
    class Meta:
        model = fileentry           ### Specify the model to connect to
        fields = ('file', )         ### This trailing comma is neccessary
        widgets = {
            'file':                 ### This is what allows you to select multiple files
                forms.ClearableFileInput(attrs={'multiple': True})}
        
class Blogform(forms.ModelForm):
    label = ''
    class Meta:
        model = Blog
        fields = ('__all__')

yoolink/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from yoolink.views import get_opening_hours
from yoolink.ycms.models import Blog


class Load_Index_Blog(ListView):
    model = Blog
    template_name = 'blog/index_blog.html'
    def get_queryset(self):
        return Blog.objects.order_by('-last_updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_opening_hours())
        return context

class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_opening_hours())
        return context

yoolink/designtemplates/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.conf import settings


def load_designtemp(request):
    
    return render(request, 'designs/overview.html')

yoolink/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

yoolink/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

yoolink/templates/pages/cms/content/sites/mainsite/AngeboteContent.html
{% extends "cmsbase.html" %}
{% load compress static %}
{% block title %} {{block.super}} | CMS - Seiteninhalt {% endblock %}

{% block content %}



<div class="container mx-auto mt-8">
    <div class="flex justify-between">
        <h1 class="text-2xl "><a href="{% url 'cms:sites' %}" class="text-blue-500">Seiten</a> / <a
                href="{% url 'cms:site_hauptseite' %}" class="text-blue-500">Hauptseite</a> / <span>Angebote</span></h1>
        <div>
            {% csrf_token %}
            <a class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mr-6 hover:cursor-pointer"
                id="saveTextData" name="main_angebote">
                Speichern
            </a>
        </div>
    </div>


    <div class="mt-8 w-full flex-col">
        <div class="flex w-full items-center justify-center md:px-8">
          <div class="mb-10 max-w-4xl sm:text-center md:mx-auto md:mb-12">
            <input class="mb-4 inline-block w-80 appearance-none rounded-lg border-2 border-gray-200 bg-gray-200 px-4 py-2 text-center text-sm font-semibold uppercase leading-tight tracking-wider text-blue-500 focus:border-blue-500 focus:bg-white focus:outline-none" id="header" type="text" value="{% if textContent and textContent.header %}{{textContent.header}}{% else %}Unsere Empfehlungen{% endif %}" />
            <input id="title" class="mb-6 inline-block w-full max-w-lg appearance-none rounded-lg border-2 border-gray-200 bg-gray-200 px-4 py-2 text-center font-sans text-3xl font-bold leading-none tracking-tight text-gray-900 focus:border-blue-500 focus:bg-white focus:outline-none sm:text-4xl md:mx-auto" value="{% if textContent and textContent.title %}{{textContent.title}}{% else %}Produkte{%endif%}" />
            <div>
               <input class="mb-4 inline-block w-80 appearance-none rounded-lg border-2 border-gray-200 bg-gray-200 px-4 py-2 text-center text-sm font-semibold leading-tight tracking-wider focus:border-blue-500 focus:bg-white focus:outline-none" id="buttonText" type="text" value="{% if textContent and textContent.buttonText %}{{textContent.buttonText}}{% else %}Alle Produkte anzeigen{% endif %}" />
            </div>
           
          </div>
        </div>
        <div class="flex items-center justify-center">
            <div class="flex flex-col rounded-2xl border-gray-200 bg-blue-100 p-6 text-black shadow-xl">
              <h2 class="mb-4 flex justify-between text-2xl font-bold">Produkte <i class="bi bi-shop"></i></h2>
              <p class="mb-4">Hier kannst du deine Produkte verwalten</p>
              <p class="mb-4">Produkte: <strong>{{product_count}}</strong></p>
              <div class="flex-grow"></div>
              <div class="mt-4 flex items-center justify-center">
                <a href="{% url 'cms:products' %}" class="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700">Verwalten</a>
                <div class="flex-grow"></div>
                <a href="{% url 'cms:product-create' %}" class="self-end rounded bg-green-600 px-4 py-2 font-bold text-white hover:bg-green-700">Erstellen</a>
              </div>
            </div>
          </div>
      </div>


    {% block javascriptend %}
    {% compress js inline %}
    <script defer src="{% static 'js/cms.js' %}"></script>
    <script src="{% static 'js/cms/content/save-text.js' %}"></script>
    {% endcompress js %}
    {% endblock javascriptend %}



    {% endblock content %}

yoolink/templates/pages/cms/content/sites/mainsite/DienstleistungenContent.html
{% extends "cmsbase.html" %}
{% load compress static %}
{% block title %} {{block.super}} | CMS - Seiteninhalt {% endblock %}

{% block content %}



<div class="container mx-auto mt-8">
    <div class="flex justify-between">
        <h1 class="text-2xl "><a href="{% url 'cms:sites' %}" class="text-blue-500">Seiten</a> / <a
                href="{% url 'cms:site_hauptseite' %}" class="text-blue-500">Hauptseite</a> / <span>Dienstleistungen</span></h1>
        <div>
            {% csrf_token %}
            <a class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mr-6 hover:cursor-pointer"
                id="saveTextData" name="main_dienstleistungen">
                Speichern
            </a>
        </div>
    </div>


    <section id="Dienstleistungen">
        <div class="mx-auto px-4 py-16 sm:max-w-xl md:max-w-full md:px-24 lg:max-w-screen-xl lg:px-8 lg:py-20">
          <div class="mb-10 max-w-xl text-center md:mx-auto md:mb-12 lg:max-w-2xl">
            <div>
              <input id="header" class="mb-4 inline-block rounded-lg px-3 py-2 w-60 text-sm font-semibold uppercase tracking-wider text-blue-500 leading-none appearance-none border-2 border-gray-200 bg-gray-200 text-center focus:bg-white focus:border-blue-500 focus:outline-none" value="{% if textContent and textContent.header %}{{textContent.header}}{% else %}Dienstleistungen{%endif%}"></input>
            </div>
            <input id="title" class="mb-6 max-w-lg font-sans text-3xl font-bold leading-none tracking-tight text-gray-900 sm:text-4xl md:mx-auto inline-block w-full appearance-none rounded-lg border-2 border-gray-200 bg-gray-200 px-4 py-2 text-center focus:bg-white focus:border-blue-500 focus:outline-none" value="{% if textContent and textContent.title %}{{textContent.title}}{% else %}Dienstleistungen{%endif%}"></input>
            <input id="buttonText" class="text-gray-700 md:text-lg w-96 inline-block rounded-lg px-3 py-2  text-sm font-semibold tracking-wider leading-none appearance-none border-2 border-gray-200 bg-gray-200 text-center focus:bg-white focus:border-blue-500 focus:outline-none" value="{% if textContent and textContent.buttonText %}{{textContent.buttonText}}{% else %}Meine Tätigkeitsbereiche{%endif%}"></input>
          </div>
          <div class="row-gap-10 mx-auto grid max-w-screen-lg gap-8 lg:grid-cols-2">
            <div class="flex max-w-full flex-col sm:mx-auto sm:max-w-md sm:flex-row">
              <div class="text-content text-center sm:text-left" key="main_dienst_1">
                <input inputType="title" class="mb-3 inline-block w-full appearance-none rounded-lg border-2 border-gray-200 bg-gray-200 px-4 py-2 text-center text-xl font-bold leading-5 tracking-tight focus:bg-white focus:border-blue-500 focus:outline-none" 
                value="{% if dienst1Text and dienst1Text.title %}{{dienst1Text.title}}{% else %}Schweißtechnik und Qualitätsmanagement{% endif %}" />
                <textarea inputType="description" class="mb-3 text-base text-gray-900 bg-gray-200 rounded-lg appearance-none border-2 border-gray-200 w-full py-2 px-4  leading-tight focus:outline-none focus:bg-white focus:border-blue-500 h-48">{% if dienst1Text and dienst1Text.description %}{{dienst1Text.description}}{% else %}In meinem Fachgebiet der Schweißtechnik konzentriere ich mich darauf, höchste Qualitätsstandards zu gewährleisten. Von der Auswahl der richtigen Schweißverfahren bis zur genauen Überwachung jedes Schweißvorgangs – meine Dienstleistungen sind darauf ausgerichtet, sicherzustellen, dass Ihre geschweißten Konstruktionen den strengsten Anforderungen entsprechen.{% endif %}</textarea>
              </div>
            </div>
            <div class="flex max-w-full flex-col sm:mx-auto sm:max-w-md sm:flex-row">
              <div class="text-content text-center sm:text-left" key="main_dienst_2">
                <input inputType="title" class="mb-3 inline-block w-full appearance-none rounded-lg border-2 border-gray-200 bg-gray-200 px-4 py-2 text-center text-xl font-bold leading-5 tracking-tight focus:bg-white focus:border-blue-500 focus:outline-none" 
                value="{% if dienst2Text and dienst2Text.title %}{{dienst2Text.title}}{% else %}Schweißinspektion und Qualitätssicherung{% endif %}" />
                <textarea inputType="description" class="mb-3 text-base text-gray-900 bg-gray-200 rounded-lg appearance-none border-2 border-gray-200 w-full py-2 px-4  leading-tight focus:outline-none focus:bg-white focus:border-blue-500 h-48">{% if dienst2Text and dienst2Text.description %}{{dienst2Text.description}}{% else %}Die Qualitätssicherung ist ein unverzichtbarer Bestandteil meiner Dienstleistungen. Durch präzise Schweißinspektionen und die Anwendung strenger Qualitätskontrollverfahren gewährleiste ich, dass Ihre geschweißten Produkte höchsten Standards entsprechen. Vertrauen Sie auf meine Expertise, um Mängel zu vermeiden und die Langlebigkeit Ihrer Konstruktionen zu sichern.{% endif %}</textarea>
              </div>
            </div>
            <div class="flex max-w-full flex-col sm:mx-auto sm:max-w-md sm:flex-row">
              <div class="text-content text-center sm:text-left" key="main_dienst_3">
                <input inputType="title" class="mb-3 inline-block w-full appearance-none rounded-lg border-2 border-gray-200 bg-gray-200 px-4 py-2 text-center text-xl font-bold leading-5 tracking-tight focus:bg-white focus:border-blue-500 focus:outline-none" 
                value="{% if dienst3Text and dienst3Text.title %}{{dienst3Text.title}}{% else %}Schweißverfahrensoptimierung{% endif %}" />
                <textarea inputType="description" class="mb-3 text-base text-gray-900 bg-gray-200 rounded-lg appearance-none border-2 border-gray-200 w-full py-2 px-4  leading-tight focus:outline-none focus:bg-white focus:border-blue-500 h-48">{% if dienst3Text and dienst3Text.description %}{{dienst3Text.description}}{% else %}Die Optimierung von Schweißverfahren ist entscheidend für die Effizienz und Qualität Ihrer Arbeit. Ich stehe Ihnen zur Seite, um innovative Lösungen zu entwickeln, Arbeitsabläufe zu optimieren und sicherzustellen, dass Sie stets die neuesten Entwicklungen in der Schweißtechnologie nutzen, um erstklassige Ergebnisse zu erzielen.{% endif %}</textarea>
              </div>
            </div>
      
            <div class="flex max-w-full flex-col sm:mx-auto sm:max-w-md sm:flex-row">
              <div class="text-content text-center sm:text-left" key="main_dienst_4">
                <input inputType="title" class="mb-3 inline-block w-full appearance-none rounded-lg border-2 border-gray-200 bg-gray-200 px-4 py-2 text-center text-xl font-bold leading-5 tracking-tight focus:bg-white focus:border-blue-500 focus:outline-none" 
                value="{% if dienst4Text and dienst4Text.title %}{{dienst4Text.title}}{% else %}Produkte{% endif %}" />
                <textarea inputType="description" class="mb-3 text-base text-gray-900 bg-gray-200 rounded-lg appearance-none border-2 border-gray-200 w-full py-2 px-4  leading-tight focus:outline-none focus:bg-white focus:border-blue-500 h-48">{% if dienst4Text and dienst4Text.description %}{{dienst4Text.description}}{% else %}Von präzisen Schweißgeräten bis zu hochwertigen Schweißzusatzwerkstoffen bieten wir Ihnen alles, was Sie für herausragende Ergebnisse benötigen. Unsere Schweißgeräte stehen für Spitzenleistung und Zuverlässigkeit, während unsere Schweißzusatzwerkstoffe die perfekte Ergänzung für starke Verbindungen sind.{% endif %}</textarea>
              </div>
            </div>
          </div>
        </div>
      </section>
      


    {% block javascriptend %}
    {% compress js inline %}
    <script defer src="{% static 'js/cms.js' %}"></script>
    <script src="{% static 'js/cms/content/save-text.js' %}"></script>
    {% endcompress js %}
    {% endblock javascriptend %}



    {% endblock content %}